name: mobile
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line
  go_router: 4.3.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.9
  flutter_svg: ^1.1.4
  dio: ^4.0.6
  multiple_result: ^1.0.4
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/shit/
